from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image
import os
import pandas as pd

def dataframe_to_table(df: pd.DataFrame):
    """
    Converts a pandas DataFrame into a ReportLab Table with styling.
    """
    data = [df.columns.tolist()] + df.values.tolist()
    table = Table(data)
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#2E86C1")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.whitesmoke),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("BOTTOMPADDING", (0, 0), (-1, 0), 8),
        ("BACKGROUND", (0, 1), (-1, -1), colors.beige),
        ("GRID", (0, 0), (-1, -1), 0.25, colors.gray),
    ]))
    return table


def generate_pdf_report(status_summary: pd.DataFrame,
                        top_5xx_paths: pd.DataFrame,
                        pie_chart_path: str,
                        bar_chart_path: str,
                        output_pdf_path: str):
    """
    Builds a complete PDF report with tables and charts.
    """
    doc = SimpleDocTemplate(output_pdf_path, pagesize=A4)
    story = []
    styles = getSampleStyleSheet()

    # Title
    story.append(Paragraph("<b>Web Application Log Report</b>", styles["Title"]))
    story.append(Spacer(1, 12))

    # Status Summary Table
    story.append(Paragraph("<b>Status Code Summary</b>", styles["Heading2"]))
    story.append(dataframe_to_table(status_summary))
    story.append(Spacer(1, 20))

    # Pie Chart
    if os.path.exists(pie_chart_path):
        story.append(Paragraph("<b>HTTP Status Code Distribution</b>", styles["Heading2"]))
        story.append(Image(pie_chart_path, width=400, height=400))
        story.append(Spacer(1, 20))

    # 5xx Analysis
    story.append(Paragraph("<b>Top Failing Paths (5xx)</b>", styles["Heading2"]))
    if not top_5xx_paths.empty:
        story.append(dataframe_to_table(top_5xx_paths))
        story.append(Spacer(1, 20))
        if os.path.exists(bar_chart_path):
            story.append(Image(bar_chart_path, width=400, height=300))
    else:
        story.append(Paragraph("No 5xx errors found in logs.", styles["Normal"]))

    # Footer
    story.append(Spacer(1, 40))
    story.append(Paragraph("Generated by Chinmay Shastri's Python Log Monitoring System", styles["Normal"]))

    doc.build(story)
    print(f"✅ PDF report generated: {os.path.abspath(output_pdf_path)}")
